apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.3'

    defaultConfig {
        applicationId 'cn.mu5120.console'
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 35
        versionName '1.3.21'
    }

    signingConfigs {
        release {
            storeFile file('../mu5120-release.jks')
            storePassword 'MU5120-111111'
            keyAlias 'mu5120'
            keyPassword 'MU5120-111111'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
